namespace: toy-msa

global:
  imageRegistry: ghcr.io/jeonnewjin/toy-msa
  imageTag: aa89595b3a4915799de795af51a1bed41106d1b5
  imagePullSecrets:
    - name: ghcr-secret
  springProfile: prd

secret:
  mysqlUsername: application
  mysqlPassword: application
  jwtSecret: ef3c624796ba503c2f44152e89b643db951fa5101bc711a7690bae2f80272790
  jwtExpiration: "86400000"

commonEnv:
  zipkinEndpoint: http://zipkin:9411/api/v2/spans
  logstashHost: logstash
  logstashPort: "5044"

apigatewayService:
  replicas: 1
  port:
    http: 8000
    management: 8081
  service:
    type: NodePort
    nodePort: 30000

userService:
  replicas: 1
  port:
    http: 8080
    management: 8081
  mysql:
    host: mysql
    port: "3306"

orderService:
  replicas: 1
  port:
    http: 8080
    management: 8081
  mysql:
    host: mysql
    port: "3306"
  grpc:
    catalogServiceHost: catalog-service
    catalogServicePort: "9091"
  kafka:
    bootstrapServers: kafka:9092

catalogService:
  replicas: 1
  port:
    http: 8080
    management: 8081
    grpc: 9091
  mysql:
    host: mysql
    port: "3306"
  kafka:
    bootstrapServers: kafka:9092
