apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: toy-msa
type: Opaque
stringData:
  mysql-username: application
  mysql-password: application
  mysql-root-password: root
  jwt-secret: ef3c624796ba503c2f44152e89b643db951fa5101bc711a7690bae2f80272790
  jwt-expiration: "86400000"
