apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: obs-grafana
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 7.x.x
    helm:
      releaseName: grafana
      values: |
        adminUser: admin
        adminPassword: admin
        service:
          type: NodePort
          nodePort: 30030
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Prometheus
                type: prometheus
                access: proxy
                url: http://prometheus-server:9090
                isDefault: true

  destination:
    server: https://kubernetes.default.svc
    namespace: toy-msa

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
