apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-prometheus
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 25.15.0
    helm:
      releaseName: prometheus
      values: |
        server:
          service:
            type: NodePort
            nodePort: 30090
        serverFiles:
          prometheus.yml:
            scrape_configs:
              - job_name: 'apigateway-service'
                metrics_path: '/actuator/prometheus'
                static_configs:
                  - targets: ['apigateway-service:8081']
              - job_name: 'user-service'
                metrics_path: '/actuator/prometheus'
                static_configs:
                  - targets: ['user-service:8081']
              - job_name: 'order-service'
                metrics_path: '/actuator/prometheus'
                static_configs:
                  - targets: ['order-service:8081']
              - job_name: 'catalog-service'
                metrics_path: '/actuator/prometheus'
                static_configs:
                  - targets: ['catalog-service:8081']
        alertmanager:
          enabled: false
        pushgateway:
          enabled: false
        kubeStateMetrics:
          enabled: false
        nodeExporter:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: toy-msa

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
