apiVersion: ps.percona.com/v1
kind: PerconaServerMySQL
metadata:
  name: mysql
  namespace: toy-msa
spec:
  secretsName: mysql-credentials
  unsafeFlags:
    mysqlSize: true
    proxySize: true
  mysql:
    clusterType: group-replication
    size: 2
    image: percona/percona-server:8.4.6-6.1
    affinity:
      antiAffinityTopologyKey: none
    volumeSpec:
      persistentVolumeClaim:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
  backup:
    image: percona/percona-xtrabackup:8.4
  proxy:
    haproxy:
      enabled: false
      size: 0
      image: percona/haproxy:2.8
    router:
      enabled: true
      size: 1
      image: percona/percona-server:8.4.6-6.1
