apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: toy-msa
type: Opaque
stringData:
  root: root
  xtrabackup: xtrabackup
  monitor: monitor
  pmmserverkey: ""
  operator: operator
  replication: replication
  orchestrator: orchestrator
  heartbeat: heartbeat
