apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-mysql-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default

  source:
    repoURL: https://percona.github.io/percona-helm-charts/
    chart: ps-operator
    targetRevision: 1.0.0
    helm:
      releaseName: ps-operator

  destination:
    server: https://kubernetes.default.svc
    namespace: toy-msa

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
