apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-strimzi-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default

  source:
    repoURL: https://strimzi.io/charts/
    chart: strimzi-kafka-operator
    targetRevision: 0.43.0
    helm:
      releaseName: strimzi-kafka-operator
      values: |
        watchNamespaces:
          - toy-msa

  destination:
    server: https://kubernetes.default.svc
    namespace: toy-msa

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
