apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-mysql-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default

  source:
    repoURL: https://canozokur.github.io/mysql-operator/
    chart: mysql-operator
    targetRevision: 2.2.x
    helm:
      releaseName: mysql-operator

  destination:
    server: https://kubernetes.default.svc
    namespace: toy-msa

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
