apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: toy-msa-kibana
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: kibana
    targetRevision: 12.1.10
    helm:
      releaseName: kibana
      values: |
        image:
          registry: docker.io
          repository: bitnamilegacy/kibana
        elasticsearch:
          hosts:
            - elasticsearch-master
          port: 9200
        service:
          type: NodePort
          nodePorts:
            http: 30601

  destination:
    server: https://kubernetes.default.svc
    namespace: toy-msa

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true