{{- if .Values.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-{{ include "order-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  stripPrefix:
    prefixes:
      - {{ .Values.ingress.stripPrefix }}
{{- end }}
