{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "catalog-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "catalog-service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "catalog-service.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: management
      path: {{ .Values.metrics.path }}
      interval: 10s
{{- end }}
