apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.orderService.replicas }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      serviceAccountName: order-service
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      containers:
        - name: order-service
          image: {{ .Values.global.imageRegistry }}/order-service:{{ .Values.global.imageTag }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .Values.orderService.port.http }}
            - name: management
              containerPort: {{ .Values.orderService.port.management }}
          envFrom:
            - configMapRef:
                name: common-env
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.global.springProfile }}
            - name: SERVER_PORT
              value: {{ .Values.orderService.port.http | quote }}
            - name: MANAGEMENT_SERVER_PORT
              value: {{ .Values.orderService.port.management | quote }}
            - name: MYSQL_HOST
              value: {{ .Values.orderService.mysql.host }}
            - name: MYSQL_PORT
              value: {{ .Values.orderService.mysql.port | quote }}
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: mysql-username
            - name: MYSQL_PWD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: mysql-password
            - name: GRPC_CLIENT_CATALOG-SERVICE_HOST
              value: {{ .Values.orderService.grpc.catalogServiceHost }}
            - name: GRPC_CLIENT_CATALOG-SERVICE_PORT
              value: {{ .Values.orderService.grpc.catalogServicePort | quote }}
            - name: BOOTSTRAP_SERVERS
              value: {{ .Values.orderService.kafka.bootstrapServers }}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.orderService.port.management }}
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.orderService.port.management }}
            initialDelaySeconds: 30
            periodSeconds: 15

---

apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
    - name: http
      port: {{ .Values.orderService.port.http }}
      targetPort: {{ .Values.orderService.port.http }}
    - name: management
      port: {{ .Values.orderService.port.management }}
      targetPort: {{ .Values.orderService.port.management }}
