apiVersion: v1
kind: ServiceAccount
metadata:
  name: apigateway-service
  namespace: {{ .Values.namespace }}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-service
  namespace: {{ .Values.namespace }}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service
  namespace: {{ .Values.namespace }}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalog-service
  namespace: {{ .Values.namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: app-service
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "pods"]
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: app-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: app-service
subjects:
  - kind: ServiceAccount
    name: apigateway-service
    namespace: {{ .Values.namespace }}
  - kind: ServiceAccount
    name: user-service
    namespace: {{ .Values.namespace }}
  - kind: ServiceAccount
    name: order-service
    namespace: {{ .Values.namespace }}
  - kind: ServiceAccount
    name: catalog-service
    namespace: {{ .Values.namespace }}
