apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  mysql-username: {{ .Values.secret.mysqlUsername }}
  mysql-password: {{ .Values.secret.mysqlPassword }}
  jwt-secret: {{ .Values.secret.jwtSecret }}
  jwt-expiration: {{ .Values.secret.jwtExpiration | quote }}
