apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: toy-msa
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      serviceAccountName: order-service
      containers:
        - name: order-service
          image: ghcr.io/jeonnewjin/toy-msa/order-service:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
            - name: management
              containerPort: 8081
          envFrom:
            - configMapRef:
                name: common-env
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prd
            - name: SERVER_PORT
              value: "8080"
            - name: MANAGEMENT_SERVER_PORT
              value: "8081"
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: mysql-username
            - name: MYSQL_PWD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: mysql-password
            - name: GRPC_CLIENT_CATALOG-SERVICE_HOST
              value: catalog-service
            - name: GRPC_CLIENT_CATALOG-SERVICE_PORT
              value: "9091"
            - name: BOOTSTRAP_SERVERS
              value: kafka-0.kafka.toy-msa.svc.cluster.local:9092
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 15

---

apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: toy-msa
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: management
      port: 8081
      targetPort: 8081
