---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-catalog-service-secret
  namespace: toy-msa
spec:
  encryptedData:
    MYSQL_PWD: AgA44ngF+2jrlOLsA6OeKoP5Tpov5aSGe5EB9v2S3MbTr2y9Z8pgjY6XUUfHQwrCxbW9gr4IAevgD1QBzYfGHeXMJRCLSD1jh8T2h9df17eThJfuumAzkWZw9hWhZ5Ei9pVlE9BScwGpHfuFlRTUUtmGrpZ5ZmC/qKfgeTt3N+uMM+DbDDyDQ9JE4+SEsIQJoowiRhhqzfUsnRTLPh7f36uHSN79zG6Dw4zwqQqoee9QRB9bnNe4yQprMEz60Sy2hQQzmYL38gIlc3znGswAJfX6ajJOvisix0Px7Ijb+JhZ7H2RfHhJ4zrCayWn+lp+ENjXFCJPJ4bJGnUO/AMwEV6m7jQmne2qv5YjJT+9nu4C7647yJcq8Ek+0zaTLTFMf7RxUXzzkqOvap5oUfHaaio4uZsO58JqFmbnVwkKEGvhOr/iUhdDcYqeTnFi914J5tDbG0CXZhTY4TM1PFHbJNFKqOfQEFpzsEg563wMRmL++hpnFrw4qHDcx0nV6cjerlfc52joamV8JIpcHBhT9k6DhsXjsJqBxIszBrGpaEYnHoT+Rg6wxPxUDsT8YCEBrhZITrqtXK60R4MJ+Oi0QWWHwPRXBY7u6kuPH0sazf7WOXe8qMgJF3VgVk5T2lEmi+cGKF1RSDxsip4U4pULqnR6GbMNZOBp2dTT9c/thh7pwYsBAlNpk4IGmldvm7GCHuPqtXwgDz7+h2bxZw==
    MYSQL_USER: AgCt4mopbkUPvl34OwK2ob9GHsPZ+ovXcrRs3erF22DtbbTgXpyRc4gL0DDJG5Ryp6ZCal7Qmdzc4q+F+kKTbfirQlAuYCv/X4NYJmlmixRP6ElPA3fTcbZJ7i8HspF/ov4HuCz5Vc23HCCzhJAqyIsGIg9TSv7jpy05/LV/lZwFERqeDIIllKOOAQKzfirtkoDqglU+b5GiONBv9CWQsb5xfyiRkIHD/hk7lHMORp+AjJ88oFY+tjMo+iBoOYi6Kz3iJ8sgO8/DI5Wsas/WmSjUojsLGEvBJsio5FSjSuJ9fZqebKiKWnBrgMIkb/+wDxSnurhrnGCdGHYh7lA5UOB6dWzc2PRUlaEPtDHBAM0h2FGY+m96duWMJU45Sf5samRIzFAC0WVJrgSqP3ByH/0+feNRbgOoimMXDjlCEuZEemch6G5ZyB2T+hFz55RjwWpOyxIpZgBCOXpnNABMpBHFI4ChM3jE14EsKCUJv+buwusAaESAqW0PVzwSqrdcBdD5Hgy/ViCqAtgxv7C6R/bWy+xqNTKobCy6nyPib9bM0pPsH8C68qmRFeuNkXhnCD+fdDWoT7BglkA4jIAf1DJy+djhQcs07WK2/bEdiUYhmaVUVIgaW14mjj7cUvTxMdXiBfq329rbOtrEPin3Z8ON/UYSG+TnMkX6ky7LdL3qshEQo5e+yaFqQpRelCmclgBnmyIYggiRcGdy0w==
  template:
    metadata:
      name: app-catalog-service-secret
      namespace: toy-msa
