---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-catalog-service-secret
  namespace: default
spec:
  encryptedData:
    MYSQL_PWD: AgBt/HrpiVysdzrsXrMTqVuddo1XEdTWvkvkxwCfaauoG0PC9hpKQu0ZEfxYsOrdkLW2f2TGtINnktOb0zhRirk9kXT3FWcJ2IfXKEHRrq2nWH8pTJiDBe2ZALK9zE3x60hHb7/Nl5OCyTdxFRjQmazTPC+ZPWXPrZVfbV3331a6Hl/TimE9Uql1/2GI9mC8ftOqAqKP+VESCSvAl1SEKdvJL9wZNgaWBKIXiTVAvvyGBtbee/KnVVnQjrF2nezLMttYoE3sD4qvWLXPyV1eUAsj8A6CaZyDla7nScoPbbXOtoIYmoDT5ZwKmyacOrCBrWMHeNdrujOF3XFHvS225owBzLg4soP8WY5Txp9/i8UeMkSmGUDgLPwf7RjzrwLSDSYB74TQDeD7svo6TBa2MlFDR+xKFSpvl2+17jBzxD9r8AqEU7Qd56t/beHU4kFKP9P9e/0hs6kMCy8yd7s7V4FZzQGwfnm10xnbn56TZAIoSlHEl72DIz2ebf4oXnbnhcX1oRbn4qgjpQbSYqSKG0KOPNcwWA4/6rO/8Uvh/1FB2JoyBubkAzOxRJD9rLcPhrpqPL0BzW58Q03pC8BoXtgTMwGZtqp11JDnOM/3OQmxn/ydBAbV7ZQaYvIMvS3SQQxqcHllO8jCr5Er6/vpA4zuV4ubGVup0GXQJxsY9SrqSHLYTkDiC28e171u5VMEiZvUF+pwlQelSj5HNg==
    MYSQL_USER: AgBUlZDYVzq6gnFLFLCroN8GJue3m27VpUnYBhHxXW4t+Cz5rP0m0Xlnl79KyEHG7mMxJ0dFgbGswGrw3tg2VY9ugVuIOvvLgyEBHuz8H/+pRMIiWTJRrKgFSoIxG+msc2JsrfjYwXrthNIH+AR4BaJlHeO8i2bqXvH9bYDuQwjb+YRk18cVS5yI3Xrpna4kNvzgCwxPcwJ7/LYRO9p3t2wAJx1w6l+ift4Q3y7qGEVoQ3b0Yk5GDB6ds0cpxLsn3wiQeNGy+Xc6FhYz1YfATcGB8BXAcUGZc+CIq7bzrTeiPc4K9MiXr/JERgX9Sdqhjuwsj665jRTuFkDVreSNBE08tvdj+aK2rHE6A6RC2XiyTm1dQmjS2AVrEIIYc0XQVPo2nskwZsPevexfZwXBrKFbvNovMEiVN/ZEuKIok23jNMpdgRa8n+AIoFbXyzw48rKF+jefAOLKGZf+hISrW4sFVC9Tm7BLMPQlQU5PmAG15zMtirSN56xDKR+Fh49ffK55Bj4w/4SbprEqFf5v58mqj9mGkyJhMFYaL93PtKlybCqOIWiEvYIf23YbcExYY0bwC7ihMkogK/6VGd3CwTimBE2/+7xQvS5jEHBYWmFM/LWced1zm0hdPFzxSHLRKSJXZDxr695voTTy+ii9ksDciqL44SayOOWDzg0lIynGl+n4wP+tfk4HvBpO3/nPiB5V7+ceu/AiasIXwA==
  template:
    metadata:
      name: app-catalog-service-secret
      namespace: default
