---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-order-service-secret
  namespace: toy-msa
spec:
  encryptedData:
    MYSQL_PWD: AgB42TURJNknanbH1pIopktTPHiQTcYXDW0X3Cc/zSZU+NiKBYNvdXJWm4M28ITrsvZI3CVfPfeI7ZN5e/7gMaAqsZGKVZGMpejrfPrd9xPNMF7JgXS2XhzGGt5ud6IKvila+iAytru3JHumaU+3ftncxxaKu7IodzEXekz6xFInqEkyMlwXD+p29+CGdaSEM4Dk1uH9IiMW4O8X4/dQ82nKVeDDzuPmxJVyu5FkdK8FFSM4HKVAM+AQDFem80IS+0p3NoOfcGppp8Avn0uPvYoPA+0wuadhf/fZJQxRwjOBwTnWxW+bFuHo5N4nq3EQ3e44Lm5qiRLKwfECE1kmqpRo3dZL0l8porH88IRhL63/2cL9YS9+cS9zGfcLwVI2w1wFQtwuF6OrhTEBAOKjdn4/Khqnxl1D4B51RQMETWQumv2W9MGyUOkIeW5LKVBp8Yic4uTFeca7CaiOHJlSDqc2yhN9ogbOgnYizGsvy8ITBC4yY7YeOeoPtwfJDigchPpEt7NkLod4BLh1F993w+Qu593NGRTzXwAb9DXKZYvTFTkg9FF7P4BJzStvoEUyp92r15l+8aERP2omdqN6gmgwanvGdrVrM1rCiJQR0QEJPAel7mMDGYdoKgyf5+mobTG6aMXllKtgJuc0oHjXz9+Q/gf5smLUCNW06SlwKRbqnBWpgWKXO3r3bKj15d5qGhNyLBNc9k52oNLc6A==
    MYSQL_USER: AgC4EgNE8A8VZmHdwcYjsNxDQhFwdjtKEpahmNowoejIMqKmQBuV9MBjKDB1ALkpcbI64q1A8stfPgF1lZqDYuiXjhWte7npUzgwFgsZ+zufppxQVpPVMJ3Jkd5TmRo7KB+jQQQbNdsAM2d/OL7MKgleUfCC3n0v2aSvkUBZQIcH1d3yRGAr63fJFYEIlhgY+FXBYtLFL7E/kd6wPvomza2C2dzwGQYc7TZ+h7dJnZc/iquiytuC3wgBydumy39fIJoKkamHR0VaepLChkOhmHFShCimtqb7fe04agT75XyW9oO76O9AwZM1xXdXLRYKFfKfxV/po8vOQKdwE7yvWtOkM49E+5+P+u2qkCUaJPo2AHkEwm49Qw10qhlHRw98RYIVLfMr/C3BXvZkjxWQJDSG+pSr6PegR8DNibog6h5nzzuar2CKQ/F9oHKi3p5IiCDuaOiVmfEtE9gHkJx9LZPzkJmQY9qsCZSvdqknwMJozq27NmfynI2f9AIzlZ//GRk+GeVlrbuw5GDMUzLLhIZ+FGaARqqT/59sb9IJ1Fg3Ah5ZTCsk6ZIUybymJVN+sI0JdJPihoRjuR/LBZiEoPFC+snkpbOH9kBjwLPSioMZnwzf3OwZIciHp33K+0m1v9emek6RiwzsXlzg2bt5DoOmLXeMcRL42t5aTzNMql9oPgYgF9mG0DbafQ0a+NSFbAGFeoxptLHo4MiUoA==
  template:
    metadata:
      name: app-order-service-secret
      namespace: toy-msa
