---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-order-service-secret
  namespace: default
spec:
  encryptedData:
    MYSQL_PWD: AgBTCoXpB5YWa4t7OsGAKiSovrP3w7+c8b3XrkdjO2Q/ljpXo5JNrziBmdlGF8gal+UEQaZ2qQv2urH5CNJuZ1cLD/S762al+i+L3A95C5rjJ+oJfieeWTaRgGr+b5vJlZ0FbYKtzUwhRQzEPstR7CTX+IKeFGDvpxwXQYtaAb1RLcWgtOu28hm7bwy88zLABn7pVgh6mvnaquWpd7A4RqJRveGacDVjBV5rzlXlOemoKaNbdL+TY6ySEz6hxvk95l9eC6m4nuXbDIpUZrUk3to8Wn95zt7GHA6mf8hNh9fVR19jbd4BUJW/w/f2QWjKWbTWipkyyl44pNMUSES+CjQF1WGhTrq3At1J75TBDa2T97lNX45UGVZ6fjA9+QPsI83CbK5Zmi80ps2yH3OceAv8P7x0Nd71ihwbXqdLq7ZXcNsjL4XdA1NTFIkVxwCoVD8AifgVfqxmI4oS/ehGXFknQyxbxjom1zXDFWdUKzUlJCXrAqtQrnmHqgtSTZWfFMJOodb8u3Z3UojmrxRLFs0MFlp4l6ZIHw8sUopB7gKKquuq48xYmmi0oK2Pug3ej3+RqVr1A1NuSr8Obznh6k/4g/nZnVncyxRAsIBtF+Gfadp7cMJSOs2ghNooblWmmrisW6+PcBjduBZojws+DGJ1epAz8uF7vPGCVjo7Koc3PJtttJmU4eFftZeJ4PFcqI2waEYxqW5BEp2LSQ==
    MYSQL_USER: AgA2flPqrylRDF/rEPqHwgOBwyZR/uTG1aW3m89WZb9Ji9RNTdyS9/c+2v2AEOtF/5rWB5fmJTKqrBtlJ5hVrAvEwPrBJoQ4L55feDlUiPI0eL3l/Mmheg7J7tq1Q8JTHbX+AqLV9jaXUYLfAnwkNxojg+N+moOF1huvzNmTQ5DgrmpSXzRLWb+7tHg6pyiDUqTQRx/oq7A+JlHkkpFlNj82UvAxf2N68uIdllvXUwQOEJZRdoG3ZNXI3jDOYzM8zgyewWa8EElaOskKugNH5uSO80AkZ2DxLVVMISQk0G7Cog6pj1r1vaek/tKF6ALCk6oqenkAr+y7EXmEUnyc1mVJkT68rM2YnjCdVYRj8aSrM6FabmizhJD40yHW6SjHs7o707Pdfe7H15G8Hml4E3BKXsy9KVm7LGhdPcffAehU7B8t6Mc7ulnp/7sfsQ+f6o4B8a1aISDnQt2ldrUx504movUw2jtlRUAwEOkyTJrTiQO7GvLexkPL+HxAfYT40jQEB0HYB0ogcOJ1mpuhTpxKudodh3Bvvz/JPtLaptUlV5pshJobrvbpWvzWvmRCvSX3WfGmtNtc3nion6Zdr0wgYgtvxN3s6VWeHv/6VPjdhFj5Eg5oE7CeP6mYWt+PM9ox1QfxikkE/0L18/ct8NK/7wdtoCKDj4SwIJzjofbSPAnHGvaCdU1F+2+avEdrYI+kLpwYgN4TUqnt+A==
  template:
    metadata:
      name: app-order-service-secret
      namespace: default
