apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: toy-msa-kafka
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: kafka
    targetRevision: 31.0.0
    helm:
      values: |
        image:
          registry: docker.io
          repository: bitnamilegacy/kafka
        replicaCount: 3
        kraft:
          clusterId: "MkU3OEVBNTcwNTJENDM2Qk"
        listeners:
          client:
            protocol: PLAINTEXT
          controller:
            protocol: PLAINTEXT
          interbroker:
            protocol: PLAINTEXT
        persistence:
          size: 5Gi
        extraConfig: |
          offsets.topic.replication.factor=3
          transaction.state.log.replication.factor=3
          transaction.state.log.min.isr=2
          default.replication.factor=3
          min.insync.replicas=2

  destination:
    server: https://kubernetes.default.svc
    namespace: toy-msa

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true