apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: toy-msa-kafka-ui
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://provectus.github.io/kafka-ui-charts
    chart: kafka-ui
    targetRevision: 0.7.x
    helm:
      releaseName: kafka-ui
      values: |
        yamlApplicationConfig:
          kafka:
            clusters:
              - name: toy-msa
                bootstrapServers: toy-msa-kafka.toy-msa.svc.cluster.local:9092

        service:
          type: NodePort
          nodePort: 30080

  destination:
    server: https://kubernetes.default.svc
    namespace: toy-msa

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true